      

      #on: [push]
      on:
        push:
          paths:
          - 'tf-manifests/Infrastructure/*'
          - '.github/workflows/build.yml'

      name: Terraform Infrastructure deployment
      defaults: #decides where the code gets checked out from   
        run:
          working-directory: tf-manifests/Infrastructure


      jobs:

          #terraform:
          build-and-deploy-infrastructure-piece:
            runs-on: ubuntu-latest
            
            #Works with CI/CD pipeline
            env:
                  ARM_CLIENT_ID: ${{secrets.TF_CLIENT_ID}}
                  ARM_CLIENT_SECRET: ${{secrets.TF_ARM_CLIENT_SECRET}}
                  ARM_SUBSCRIPTION_ID: ${{secrets.TF_SUBSCRIPTION_ID}}
                  ARM_TENANT_ID: ${{secrets.TF_TENANT_ID}}

            steps:
            - name: Check out source code
              uses: actions/checkout@v2


            # Only works when you run terraform locally 
            # - name: Login to Azure
            #   uses: azure/login@v1
            #   with:
            #     creds: ${{ secrets.AZURE_CREDENTIALS }}
            
            - name: print path
              run: echo 'root directory --> ${{ github.workspace }}'


            # - name: Check out source code
            #   uses: actions/checkout@v2

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v1

            - name: Terraform Init
              #run: terraform  -chdir=tf-manifests init
              run: terraform  init

            # - name: Terraform state
            #   run: terraform  -chdir=tf-manifests state list

            #- name: Terraform Format
            #  run: terraform fmt -check

            # - name: Terraform Plan
            #   run: terraform -chdir=tf-manifests plan

            # - name: State file unlock
            #   run: terraform force-unlock 58dad817-b2b3-f223-c548-2041ffb063cb

            - name: Terraform Apply
              #run: terraform -chdir=tf-manifests apply  -auto-approve
              run: terraform  apply -auto-approve

            # - name: Upload artifact
            #   uses: action/upload-artifact@v1
            #   with:
            #     name: azcopy-logs
            #     #path: /home/runner/.azcopy/**
            #     path: ${{ github.workspace}}/../../../.azcopy/**
