      

      #on: [push]
      on:
        push:
          paths:
          - 'tf-manifests/Infrastructure/*'
          - '.github/workflows/build.yml'

      name: Terraform Infrastructure deployment
      defaults: #decides where the code gets checked out   
        run:
          working-directory: tf-manifests/Infrastructure


      jobs:

          #terraform:
          build-and-deploy-infrastructure-piece:
            runs-on: ubuntu-latest
            
            #Works with CI/CD pipeline
            env:
                  ARM_CLIENT_ID: ${{secrets.TF_CLIENT_ID}}
                  ARM_CLIENT_SECRET: ${{secrets.TF_ARM_CLIENT_SECRET}}
                  ARM_SUBSCRIPTION_ID: ${{secrets.TF_SUBSCRIPTION_ID}}
                  ARM_TENANT_ID: ${{secrets.TF_TENANT_ID}}

            steps:
            - name: Check out source code
              uses: actions/checkout@v2

            
            - name: print path
              run: echo 'root directory --> ${{ github.workspace }}'


            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v1
              with:
                terraform_wrapper: false

            - name: Terraform Init
              #run: terraform  -chdir=tf-manifests init
              run: terraform  init


            - name: Terraform Apply
              #run: terraform -chdir=tf-manifests apply  -auto-approve
              run: terraform  apply -auto-approve

            #- name: Output RG Name
            - id: a
              run: echo "::set-output name=rg::$(terraform output myResumeRG)"
              


