      

      #on: [push]
      on:
        push:
          paths:
          - 'tf-manifests/Infrastructure/*'
          - 'code/backend/**'
          - 'code/frontend/**'
          - '.github/workflows/build.yml'
      #on:
      #  workflow_dispatch:

      name: Terraform Infrastructure deployment
      defaults: #decides where the code gets checked out   
        run:
          working-directory: tf-manifests/Infrastructure


      jobs:

          #terraform:
          build-and-deploy-infrastructure-piece:
            runs-on: ubuntu-latest
            
            #Works with CI/CD pipeline
            env:
                  ARM_CLIENT_ID: ${{secrets.TF_CLIENT_ID}}
                  ARM_CLIENT_SECRET: ${{secrets.TF_ARM_CLIENT_SECRET}}
                  ARM_SUBSCRIPTION_ID: ${{secrets.TF_SUBSCRIPTION_ID}}
                  ARM_TENANT_ID: ${{secrets.TF_TENANT_ID}}

            steps:
            - name: Check out source code
              uses: actions/checkout@v2

            
            - name: print path
              run: echo 'root directory --> ${{ github.workspace }}'


            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v1
              with:
                terraform_wrapper: false

            - name: Terraform Init
              #run: terraform  -chdir=tf-manifests init
              run: terraform  init


            - name: Terraform Apply
              #run: terraform -chdir=tf-manifests apply  -auto-approve
              run: terraform  apply -auto-approve

            
        
            - id: retrieve_rg_name
              run: |
                rgname=$(terraform output resource_group_name)
                echo "::set-output name=rg::$rgname"

            - id: retrieve_func_url
              run: |
                 funcurl=$(terraform output func_app_url)
                 echo "::set-output name=func_url::$funcurl"
                
            - name: check the output from func url retrieval
              run: echo ${{ steps.retrieve_func_url.outputs.func_url }}

            - name: update main.js file
              shell: bash
              working-directory: code/frontend
              run: |
                 ls
                 filename="main.js"
                 find="const localApi = 'http://localhost:7071/api/GetResumeCounter';"
                 replace="const functionApi = ${{ steps.retrieve_func_url.outputs.func_url }};"
                 #replace="const functionApi = `echo ${{ steps.retrieve_func_url.outputs.func_url }}`;"
                 sed -i "s|$find|$replace|i" $filename
                 verify=$(cat main.js | grep "getresumecounterfunc4eb04f7")
                 echo $verify
            
            - name: login via az cli
              uses: azure/login@v1
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: and display something
              uses: azure/CLI@v1
              with:
                  azcliversion: 2.0.72
                  inlineScript: |
                              az account set -s ${{secrets.TF_SUBSCRIPTION_ID}}
                              az storage account list  -g ${{ steps.retrieve_rg_name.outputs.rg }} --query "[0].{name:name}" --output tsv

                
            outputs:
              output1: ${{ steps.retrieve_rg_name.outputs.rg }}
              output2: ${{ steps.retrieve_func_name.outputs.func }}
              output3: ${{ steps.retrieve_func_url.outputs.func_url }}

            
                 




